# Generated by Django 4.2.6 on 2023-12-21 23:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='uploadedImages')),
            ],
            options={
                'verbose_name_plural': 'Postadores',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data_de_publicacao', models.DateField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='publicacao_capa')),
                ('postador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornal_web.postador')),
                ('tags', models.ManyToManyField(to='jornal_web.tags')),
            ],
            options={
                'verbose_name_plural': 'Publicações',
            },
        ),
    ]
