# Generated by Django 4.2.6 on 2023-12-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postador',
            options={'verbose_name_plural': 'Postadores'},
        ),
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='publicacao',
            name='tags',
            field=models.ManyToManyField(to='jornal_web.tags'),
        ),
    ]
